version: '3'

services:
  app:
    build:
      context: .
      dockerfile: tools/docker/app/app.dev.docker
      args:
        DOCKER_XDEBUG_PORT: ${DOCKER_XDEBUG_PORT:-9000}
        DOCKER_XDEBUG_HEADER: ${DOCKER_XDEBUG_HEADER:-""}
    user: ${DOCKER_PHP_USER_ID}:${DOCKER_PHP_GROUP_ID}
    environment:
      CONTAINER_ROLE: "fpm"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      REDIS_PORT: "6379"
      REDIS_HOST: "redis"
    volumes:
      - '.:/var/www/app'
    depends_on:
      - postgres
      - redis

  web:
    image: gcr.io/voziv-web/house-frontend:latest
    volumes:
      - '.:/var/www/app'
    environment:
      PHP_FPM_HOST: "app"
      VIRTUAL_HOST: "house.test"
    depends_on:
      - app

  postgres:
    image: 'timescale/timescaledb:2.0.0-pg12'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'house-postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - 'house-redis:/data'

  mailhog:
    image: 'mailhog/mailhog:v1.0.0'
    environment:
      VIRTUAL_HOST: 'mailhog.house.test'
      VIRTUAL_PORT: '8025'
volumes:
  house-postgres:
    driver: local
  house-redis:
    driver: local
